version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10.0.2-jdk-sid-node-browsers
    steps:
      - checkout
      - run:
          name: Enable Gradle wrapper script execution.
          command: chmod +x ./gradlew
      - run:
          name: Build the server.
          command: ./gradlew build
