version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk-sid-browsers
    steps:
      - checkout
      - run:
          name: Enable Gradle wrapper script execution
          command: chmod +x ./gradlew
      - run:
          name: Build the server
          command: ./gradlew build
      - run:
          name: Gather coverage results
          command: ./gradlew jacocoTestReport
      - run:
          name: Upload coverage to Codecov
          command: >-
            sudo apt-get update
            && sudo apt-get install bash
            && sudo apt-get install curl
            && bash -c "bash <(curl -s https://codecov.io/bash)"
      - store_artifacts:
          path: /build/reports/checkstyle
      - store_artifacts:
          path: /build/reports/spotbugs
