env:
  browser: true
  es6: true
  jquery: true
extends: 
  - 'eslint:recommended'
  - 'plugin:backbone/recommended'
plugins:
  - backbone
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
