env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    modules: true
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
